//LOCALHOST

GET http://localhost:8080/contacts 
# Contact JSON with contact information from MongoDB #
###
#------------------------ GET :ids ---------------------------#
GET http://localhost:8080/contacts/63bc9ba020a116e9df68b1ea

###
GET http://localhost:8080/contacts/63bc9bde20a116e9df68b1eb

###
GET http://localhost:8080/contacts/63bc9c5620a116e9df68b1ec

###
GET http://localhost:8080/contacts/63bc9c9920a116e9df68b1ed

###
GET http://localhost:8080/contacts/63bc9cd720a116e9df68b1ee

###
GET http://localhost:8080/contacts/63bc9d1720a116e9df68b1ef

###
#------------------------ POST ---------------------------#
POST http://localhost:8080/contacts HTTP/1.1 content-type:application/json

{
    "fname":"Test","lname":"POST","email":"post@post.post","favoriteColor":"post purple","birthday":"post 2000"
}

###
#------------------------ PUT :ids -----------------------------#
PUT http://localhost:8080/contacts/63d04d3b99b8fbcaf1957159 HTTP/1.1 content-type:application/json
{
    "fname":"Test","lname":"Update","email":"update@update.update","favoriteColor":"update brown","birthday":"05/05/2005"
}


###
#------------------------ DELETE :ids --------------------------#
DELETE http://localhost:8080/contacts/63d04d3b99b8fbcaf1957159 HTTP/1.1 