//LOCALHOST

GET http://localhost:8080/contacts 
# Contact JSON with contact information from MongoDB #
###
#------------------------ GET :ids ---------------------------#
GET http://localhost:8080/contacts/63d2df9b6b443d1eebc7fdb0

###
GET http://localhost:8080/contacts/63d2e0cb6b443d1eebc7fdb1

###
GET http://localhost:8080/contacts/63d2e1216b443d1eebc7fdb2

###
GET http://localhost:8080/contacts/63d2e1456b443d1eebc7fdb3

###
GET http://localhost:8080/contacts/63d2e1666b443d1eebc7fdb4

###
GET http://localhost:8080/contacts/63d2e1916b443d1eebc7fdb5

###
#------------------------ POST ---------------------------#
POST http://localhost:8080/contacts HTTP/1.1 
content-type: application/json

{
    "fname":"Test",
    "lname":"POST",
    "email":"post@post.post",
    "favoriteColor":"post purple",
    "birthday":"post 2000"
}

###
#------------------------ PUT :ids -----------------------------#
PUT http://localhost:8080/contacts/63d0681fc86e60cf94bbb13c HTTP/1.1 
content-type: application/json

{
    "fname":"Test",
    "lname":"Update",
    "email":"update@update.update",
    "favoriteColor":"update brown",
    "birthday":"05/05/2005"
}


###
#------------------------ DELETE :ids --------------------------#
DELETE http://localhost:8080/contacts/63d04d3b99b8fbcaf1957159 HTTP/1.1 

###

#--------------------------- 4 RENDER ---------------------------#
#__________________________ GET CONTACTS ________________________#
GET https://ag341.onrender.com/contacts

###
#_______________________ GET SINGLE CONTACT _____________________#

GET https://ag341.onrender.com/contacts/63d2df9b6b443d1eebc7fdb0

###
#______________________________ POST ____________________________#
POST http://ag341.onrender.com/contacts HTTP/1.1 
content-type: application/json

{
    "firstName":"Test",
    "lastName":"POST",
    "email":"post@post.post",
    "favoriteColor":"post purple",
    "birthday":"post 2000"
}

###
#_____________________________ PUT :ids __________________________#
PUT http://ag341.onrender.com/contacts/63d2e8b66b443d1eebc7fdb8 HTTP/1.1 
content-type: application/json

{
    "firstName":"Test",
    "lastName":"Update",
    "email":"update@update.update",
    "favoriteColor":"update brown",
    "birthday":"05/05/2005"
}

###
#_________________________ DELETE :ids ___________________________#
DELETE http://localhost:8080/contacts/63d2e8b66b443d1eebc7fdb8 HTTP/1.1 